apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      containers:
        - image: ${IMAGE}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: DB_USERNAME
                  key: latest
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: DB_PASSWORD
                  key: latest
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: DB_DATABASE
                  key: latest
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: DB_HOST
                  key: latest
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: DB_PORT
                  key: latest
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: JWT_SECRET
                  key: latest
            - name: JWT_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: JWT_EXPIRE
                  key: latest
            - name: NODE_ENV
              value: $NODE_ENV
            - name: PSQL_DB_SCHEMA
              value: "pipeline"
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
